### PR TITLE
Update to new conda

### LINKED ISSUE #1: AttributeError: module 'conda_build.source' has no attribute 'WORK_DIR'
It appears your Python downloader doesn't work with the latest conda anymore. conda_build.source doesn't seem to have a WORK_DIR value any more.

### PR DESCRIPTION
**Pull request by mithro**
Fixes #1.

Seems to work for me, don't know if this is the best way. I was pondering if the code should extract the source into the llvm directory, but I think this ends up being better.

### CODE REVIEW

**Comment by stuarteberg** [comment]
Thanks for looking into this.  I've been meaning to update this code to work with conda 2.0 for a while now, but haven't gotten around to it.

I gave your changes a try using a [different recipe](https://github.com/ilastik/numpy-allocation-tracking/tree/master/conda-recipe), in which the "extra" source is a git repo instead of a tarball.  On that recipe, it doesn't work.  Any ideas?

PS -- just to cross-reference some related discussions:

- https://github.com/bioconda/bioconda-recipes/pull/2577
- https://github.com/conda/conda-build/issues/1466

Ultimately, it would be great if one of us could propose a PR to conda-build itself.

**Comment by mithro** [comment]
I'm using it in recipe with git https://github.com/timvideos/conda-hdmi2usb-packages/blob/master/or1k/gcc-newlib/meta.yaml and it works fine for me? Can you include errors?

I haven't tested on Windows/Mac - only Linux...

**Comment by mithro** [comment]
I have been able to repo your problem.

The problem is that with a git source (and probably other repository based checkouts) is that the contents end up directly into the `work_dir` where as normally with a archives you end up with with things inside a directory (but I guess that wouldn't be true for all of them...)

**Comment by mithro** [comment]
This interacts very weirdly with the "single directory work dir" - https://github.com/conda/conda-build/blob/master/conda_build/config.py#L509-L513
